spring.application.name=distributed-queue
spring.datasource.url=jdbc:postgresql://localhost:5433/distributed_queue
spring.datasource.username=queue_user
spring.datasource.password=queue_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
